apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-config
  namespace: {{.namespace}}
data:
  etcd.conf: |-
    # Time (in milliseconds) of a heartbeat interval.
    heartbeat-interval: 100

    # Time (in milliseconds) for an election to timeout.
    election-timeout: 1000

    # Maximum number of snapshot files to retain (0 is unlimited).
    max-snapshots: 5

    # Maximum number of wal files to retain (0 is unlimited).
    max-wals: 5

    # Comma-separated white list of origins for CORS (cross-origin resource sharing).
    cors:

    # Reject reconfiguration requests that would cause quorum loss.
    strict-reconfig-check: false

    # Accept etcd V2 client requests
    enable-v2: true

    # Enable runtime profiling data via HTTP server
    enable-pprof: true

    # Valid values include 'on', 'readonly', 'off'
    proxy: 'off'

    # Time (in milliseconds) an endpoint will be held in a failed state.
    proxy-failure-wait: 5000

    # Time (in milliseconds) of the endpoints refresh interval.
    proxy-refresh-interval: 30000

    # Time (in milliseconds) for a dial to timeout.
    proxy-dial-timeout: 1000

    # Time (in milliseconds) for a write to timeout.
    proxy-write-timeout: 5000

    # Time (in milliseconds) for a read to timeout.
    proxy-read-timeout: 0

    client-transport-security:
    # Path to the client server TLS cert file.
    cert-file:

    # Path to the client server TLS key file.
    key-file:

    # Enable client cert authentication.
    client-cert-auth: false

    # Path to the client server TLS trusted CA cert file.
    trusted-ca-file:

    # Client TLS using generated certificates
    auto-tls: false

    peer-transport-security:
    # Path to the peer server TLS cert file.
    cert-file:

    # Path to the peer server TLS key file.
    key-file:

    # Enable peer client cert authentication.
    client-cert-auth: false

    # Path to the peer server TLS trusted CA cert file.
    trusted-ca-file:

    # Peer TLS using generated certificates.
    auto-tls: false

    # Enable debug-level logging for etcd.
    debug: false

    logger: zap

    # Specify 'stdout' or 'stderr' to skip journald logging even when running under systemd.
    log-outputs: [stderr]

    # Force to create a new one member cluster.
    force-new-cluster: false

    auto-compaction-mode: periodic
    auto-compaction-retention: 1

    {{- if .quotalimit }}
    quota-backend-bytes: {{.quotalimit}}
    {{- end }}
